name: Auto Incremental Update Rules

on:
  issues:
    types: [opened, edited]

jobs:
  create-pr-for-incremental-update:
    if: contains(github.event.issue.labels.*.name, '自动化请求') && contains(github.event.issue.labels.*.name, '增量更新')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Check issue body
        id: issue-body
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body;
            
            // 提取表单字段
            const extractField = (fieldName) => {
              const match = body.match(new RegExp(`### ${fieldName}\\s*\\n\\s*([^\\n]+)`));
              return match ? match[1].trim() : null;
            };
            
            const extractTextarea = (fieldName) => {
              const match = body.match(new RegExp(`### ${fieldName}\\s*\\n\\s*([\\s\\S]+?)(?=###|$)`));
              return match ? match[1].trim() : null;
            };
            
            const appName = extractField('应用名');
            const packageName = extractField('包名');
            const operationType = extractField('操作类型');
            const activityOperations = extractTextarea('Activity操作详情');
            const packageEnable = extractField('包启用状态');
            const disableVersionCode = extractField('禁用版本代码 \\(可选\\)');
            const userEmail = extractField('您的邮箱');
            const description = extractTextarea('修改说明');
            
            if (!packageName || !activityOperations) {
              core.setFailed('缺少必要的包名或操作详情信息');
            }
            
            // 如果没有提供邮箱，使用GitHub noreply邮箱
            let finalEmail = userEmail;
            if (!finalEmail || finalEmail == "_No response_") {
              finalEmail = `${context.payload.issue.user.id}+${context.payload.issue.user.login}@users.noreply.github.com`;
            }
            
            return {
              appName,
              packageName,
              operationType,
              activityOperations,
              packageEnable: packageEnable || "不修改",
              disableVersionCode,
              userEmail: finalEmail,
              userName: context.payload.issue.user.login,
              description
            };

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Make script executable
        run: chmod +x scripts/incremental_rule_updater.py

      - name: Validate package existence (for non-add operations)
        id: validate-package
        uses: actions/github-script@v7
        env:
          PACKAGE_NAME: ${{ fromJSON(steps.issue-body.outputs.result).packageName }}
          OPERATIONS: ${{ fromJSON(steps.issue-body.outputs.result).activityOperations }}
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // 读取XML文件
            const xmlPath = path.join(process.env.GITHUB_WORKSPACE, 'module', 'immerse_rules.xml');
            const xmlContent = fs.readFileSync(xmlPath, 'utf8');
            
            // 检查包是否存在
            const packagePattern = new RegExp(`<package name="${process.env.PACKAGE_NAME}"[^>]*>`);
            const packageExists = packagePattern.test(xmlContent);
            
            // 检查操作中是否只有ADD操作
            const operations = process.env.OPERATIONS.split('\n').filter(op => op.trim());
            const hasNonAddOperations = operations.some(op => 
              !op.trim().startsWith('ADD:') && op.trim().length > 0
            );
            
            if (!packageExists && hasNonAddOperations) {
              core.setFailed(`包 ${process.env.PACKAGE_NAME} 不存在，无法执行修改或删除操作`);
            }
            
            return { packageExists, hasNonAddOperations };

      - name: Apply incremental updates
        env:
          PACKAGE_NAME: ${{ fromJSON(steps.issue-body.outputs.result).packageName }}
          OPERATIONS: ${{ fromJSON(steps.issue-body.outputs.result).activityOperations }}
          PACKAGE_ENABLE: ${{ fromJSON(steps.issue-body.outputs.result).packageEnable }}
          DISABLE_VERSION_CODE: ${{ fromJSON(steps.issue-body.outputs.result).disableVersionCode }}
        run: |
          python3 scripts/incremental_rule_updater.py \
            --xml-path "module/immerse_rules.xml" \
            --package-name "$PACKAGE_NAME" \
            --operations "$OPERATIONS" \
            --enable "$PACKAGE_ENABLE" \
            ${DISABLE_VERSION_CODE:+--disable-version-code "$DISABLE_VERSION_CODE"}

      - name: Update XML with comments for new packages
        if: ${{ !fromJSON(steps.validate-package.outputs.result).packageExists }}
        uses: actions/github-script@v7
        env:
          APP_NAME: ${{ fromJSON(steps.issue-body.outputs.result).appName }}
          PACKAGE_NAME: ${{ fromJSON(steps.issue-body.outputs.result).packageName }}
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // 读取XML文件
            const xmlPath = path.join(process.env.GITHUB_WORKSPACE, 'module', 'immerse_rules.xml');
            let xmlContent = fs.readFileSync(xmlPath, 'utf8');
            
            // 为新添加的包添加注释
            if (process.env.APP_NAME) {
              const commentPattern = new RegExp(`(\\s*)<package name="${process.env.PACKAGE_NAME}"([^>]*>)`);
              const replacement = `$1<!-- ${process.env.APP_NAME} -->\n$1<package name="${process.env.PACKAGE_NAME}"$2`;
              
              if (commentPattern.test(xmlContent)) {
                xmlContent = xmlContent.replace(commentPattern, replacement);
                fs.writeFileSync(xmlPath, xmlContent, 'utf8');
                console.log('已为新包添加应用名注释');
              }
            }

      - name: Validate XML syntax
        run: |
          python3 -c "
          import xml.etree.ElementTree as ET
          try:
              ET.parse('module/immerse_rules.xml')
              print('XML语法验证通过')
          except ET.ParseError as e:
              print(f'XML语法错误: {e}')
              exit(1)
          "

      - name: Check for changes
        id: changes
        run: |
          git add module/immerse_rules.xml
          if git diff --cached --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in XML file"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in XML file"
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            Incremental update rules based on issue #${{ github.event.issue.number }}
            
            Co-authored-by: ${{ fromJSON(steps.issue-body.outputs.result).userName }} <${{ fromJSON(steps.issue-body.outputs.result).userEmail }}>
          title: "增量规则更新: ${{ fromJSON(steps.issue-body.outputs.result).packageName }}"
          body: |
            close #${{ github.event.issue.number }}

            由Issue #${{ github.event.issue.number }}自动生成的增量更新
            
            修改内容:
            - 应用名: ${{ fromJSON(steps.issue-body.outputs.result).appName || '未提供' }}
            - 包名: ${{ fromJSON(steps.issue-body.outputs.result).packageName }}
            - 操作类型: ${{ fromJSON(steps.issue-body.outputs.result).operationType }}
            - 包启用状态: ${{ fromJSON(steps.issue-body.outputs.result).packageEnable }}
            ${{ fromJSON(steps.issue-body.outputs.result).disableVersionCode && format('- 禁用版本代码: {0}', fromJSON(steps.issue-body.outputs.result).disableVersionCode) || '' }}
            
            **操作详情:**
            ```
            ${{ fromJSON(steps.issue-body.outputs.result).activityOperations }}
            ```
            
            **修改说明:**
            ${{ fromJSON(steps.issue-body.outputs.result).description || '无详细说明' }}
            
            此PR由增量更新工作流自动创建
          branch: automation/incremental-update-${{ github.event.issue.number }}
          base: main
          labels: |
            自动化
            增量更新
          delete-branch: true

      - name: Handle no changes
        if: steps.changes.outputs.has_changes == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.issue.number }},
              body: '⚠️ 处理完成，但未检测到任何更改。请检查提供的操作是否正确或文件是否已经包含相同的配置。'
            });

      - name: Associate PR with Issue
        if: steps.create-pr.outputs.pull-request-number != ''
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ steps.create-pr.outputs.pull-request-number }};
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.issue.number }},
              body: `✅ 已自动创建增量更新PR [#${prNumber}](https://github.com/${context.repo.owner}/${context.repo.repo}/pull/${prNumber}) 来处理此请求。`
            });